services:
  database:
    container_name: pool-postgres-dev
    image: postgres:16.0-alpine3.18
    ports:
      - 5432:5432
    env_file:
      - ../.env.development

  redis:
    container_name: pool-redis-dev
    image: redis:8.0-M03-bookworm
    ports:
      - 6379:6379

  mailcatcher:
    container_name: pool-mailcatcher
    image: sj26/mailcatcher
    expose:
      - "${EMAIL_SMTP_PORT}"
      - "${EMAIL_HTTP_PORT}"
    ports:
      - "${EMAIL_SMTP_PORT}:1025"
      - "${EMAIL_HTTP_PORT}:1080"
