services:
  database:
    container_name: postgres-dev
    image: postgres:16.0-alpine3.18
    ports:
      - 5432:5432
    env_file:
      - ../.env.development

  redis:
    container_name: redis-dev
    image: redis:8.0-M03-bookworm
    ports:
      - 6379:6379
