name: Production Deployment

on:
  push:
    branches:
      - stage

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: stage
      url: ${{vars.URL}}
    steps:
      - name: Build Docker image
        run: docker build -t pool-brasil .

      - name: Get Docker image tarball
        run: docker save -o pool-brasil.tar pool-brasil:latest

      - name: Deployment
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
          TARGET: "public/poolbrasil/stage"
          SOURCE: pool-brasil.tar.gz
          REMOTE_HOST: ${{vars.REMOTE_HOST}}
          REMOTE_USER: ${{vars.REMOTE_USER}}
